- modules/vshn-lbaas-hieradata/files/commit-hieradata.sh
Previously, there were cases (e.g. multiple terraform runs with the same local state where the `${branch}` already exists locally) where `git push origin ${branch}` would implicitly push `${branch}` to `master` in the remote hieradata repo. This commit adjusts the push command to always push the local `${branch}` to a matching remote `${branch}`.
> vshn-lbaas-hieradata: Correctly push feature branch

- modules/vshn-lbaas-hieradata/templates/hieradata.yaml.tmpl
Don't add the `profile_openshift4_gateway::internal_vip` key in the resulting hieradata configuration, if variable `internal_vip` is empty
> vshn-lbaas-hieradata: Render valid hieradata if internal_vip is empty

- modules/vshn-lbaas-cloudscale/files/register-server.sh
`/bin/sh` (usually dash) doesn't support `-o pipefail`.
> vshn-lbaas-cloudscale: Don't use `-o pipefail` in /bin/sh script

- modules/vshn-lbaas-cloudscale/hiera.tf
- modules/vshn-lbaas-cloudscale/variables.tf
- modules/vshn-lbaas-hieradata/main.tf
- modules/vshn-lbaas-hieradata/templates/hieradata.yaml.tmpl
- modules/vshn-lbaas-hieradata/variables.tf
This allows users to make use of the new parameters in `profile_openshift4_gateway` which allows selecting a K8s distribution and ingress controller for which the LBs should be configured.
See https://git.vshn.net/vshn-puppet/profile_openshift4_gateway/-/merge_requests/5 for the puppet profile MR.
> Add support for distribution-aware configuration of the LBs

- modules/vshn-lbaas-cloudscale/main.tf
This adds PTR records for all cloudscale VIPs. I decided to use `ingress.`, `egress.`, and `api.` as this currently seems to be the most likely setup used in [OCP-301 (internal)](https://ticket.vshn.net/browse/OCP-301)
closes https://github.com/appuio/terraform-modules/issues/12
> Add PTR record for cloudscale VIPs

- modules/vshn-lbaas-cloudscale/main.tf
- modules/vshn-lbaas-exoscale/main.tf
Puppet 7 is now mandatory. See VT-1660.
> Upgrade to Puppet 7

- modules/vshn-lbaas-exoscale/files/register-server.sh
We prepare the zone value in the module, but didn't actually pass it to the control.vshn.net API: https://github.com/appuio/terraform-modules/blob/abc8f485fed9f0534550e19273937593f0ddd40e/modules/vshn-lbaas-exoscale/main.tf#L151-L168
This commit updates the register-server script to also set the zone in the encdata.
Split out from #30 
> vshn-lbaas-exoscale: Set encdata zone for LB VMs

- modules/vshn-lbaas-exoscale/README.md
- modules/vshn-lbaas-exoscale/hiera.tf
- modules/vshn-lbaas-exoscale/main.tf
- modules/vshn-lbaas-exoscale/outputs.tf
- modules/vshn-lbaas-exoscale/providers.tf
- modules/vshn-lbaas-exoscale/security_groups.tf
- modules/vshn-lbaas-exoscale/variables.tf
Remove all usages of deprecated Exoscale Terraform resources in the `vshn-lbaas-exoscale` module. This PR requires manual actions to update the Terraform state of existing clusters. Most resources can be migrated by removing the old resource from the state and importing the object using the new resource type. Please see https://github.com/appuio/component-openshift4-terraform/pull/61 for more details and a script which performs the state migration.
Related to https://github.com/appuio/terraform-openshift4-exoscale/issues/59
> vshn-lbaas-exoscale: Update module for Exoscale provider v0.41.0

- modules/vshn-lbaas-exoscale/hiera.tf
- modules/vshn-lbaas-exoscale/variables.tf
We use the newly available `exoscale_iam_access_key` resource to generate an Exoscale API key and secret for Floaty. This allows us to remove the corresponding steps in the install instructions, see https://github.com/appuio/openshift4-docs/pull/208.
> vshn-lbaas-exoscale: Generate Floaty IAM API key via Terraform

- modules/vshn-lbaas-exoscale/README.md
- modules/vshn-lbaas-exoscale/main.tf
- modules/vshn-lbaas-exoscale/variables.tf
This was implemented for cloudscale.ch in #29, this PR ensures that we roughly keep feature parity between the cloudscale.ch and the Exoscale LB modules.
> vshn-lbaas-exoscale: Allow users to customize the LB instance type

- modules/vshn-lbaas-exoscale/security_groups.tf
This PR fixes an oversight in #30 where we refactored the security group rules and mistakenly included the Kubernetes API port in the ports to open for UDP traffic. Additionally, the PR ensures that the descriptions for the security group rules don't change, so that we can avoid having to recreate rules when migrating state for existing clusters.
Labeled `ignore` since this PR doesn't need to be included in the changelog.
> vshn-lbaas-exoscale: Adjust security group rules to simplify migration of existing clusters

- modules/vshn-lbaas-exoscale/main.tf
The new Terraform resource `exoscale_compute_instance` doesn't support setting the instance's display name. To ensure we get the instance FQDNs as display names, we use the FQDNs for field `name`. Usually this would configure the instance (through cloud-init) to use its FQDN as its hostname, but we provide a custom cloud-init configuration already which sets the hostname correctly.
Follow-up to #30 
> vshn-lbaas-exoscale: Use FQDN as compute instance `name`

- modules/vshn-lbaas-exoscale/README.md
- modules/vshn-lbaas-exoscale/main.tf
- modules/vshn-lbaas-exoscale/variables.tf
Follow-up to #30. When upgrading the Exoscale Terraform provider, we assumed that we can still pass arbitrary affinity group IDs to instances through `anti_affinity_group_ids`, but that parameter has been changed to only accept anti-affinity groups, while there's a new parameter `deploy_target_id` for other affinity group IDs, such as the one necessary to schedule instances on dedicated hypervisors.
> vshn-lbaas-exoscale: Add support for configuring deployment target ID

- modules/vshn-lbaas-exoscale/hiera.tf
- modules/vshn-lbaas-exoscale/variables.tf
Exoscale's new IAM API (v3) isn't yet supported by the Terraform provider, so we switch back to expecting users to provide the Floaty IAM key as an input variable in the vshn-lbaas-exoscale module.
This reverts #33 (commit a56cbb961f2d14b8d96f602b810e5eaff34fedcf), reversing changes made to 9825ee9bf759232d295f06c01d29fd515939643c.
> vshn-lbaas-exoscale: Switch back to user-provided IAM key for Floaty

- modules/vshn-lbaas-exoscale/main.tf
Since provider version v0.43.0, the `exoscale_elastic_ip` resource supports configuring reverse DNS again.
Provider update in #41 
See also #30 
> vshn-lbaas-exoscale: Manage Elastic IP reverse DNS with Terraform

- modules/vshn-lbaas-exoscale/main.tf
The `exoscale_compute_template` data source has been deprecated in favor of the `exoscale_template` data source.
With this change, the `vshn-lbaas-exoscale` module doesn't use any "compute-legacy" API endpoints anymore, which makes working with IAM v3 a bit easier.
Follow-up to #41 
> vshn-lbaas-exoscale: Switch to new `exoscale_template` data source

- modules/vshn-lbaas-exoscale/security_groups.tf
We add explicit rules for SSH to the LBs in the LB security group as preparation for removing the SSH from anywhere rule from the `all_machines` security group in terraform-openshift4-exoscale.
See also https://github.com/appuio/terraform-openshift4-exoscale/issues/78
> vshn-lbaas-exoscale: Update LB security group to allow SSH to the LBs from anywhere

- modules/vshn-lbaas-exoscale/hiera.tf
- modules/vshn-lbaas-exoscale/variables.tf
This PR introduces Terraform-managed IAMv3 credentials for Floaty on Exoscale. The IAMv3 role should be suitable for Floaty v1.1 and the future Floaty versions which will switch to Exoscale's compute v2 API.
Please note that this is a breaking change for clusters that were setup with or upgraded to terraform-modules v4. Operators will need to manually ensure that the old Terraform-managed Floaty credentials won't be invalidated before the new credentials are put in place on the LB VMs via VSHN's Puppet infrastructure.
We'll provide detailed instructions for the migration to terraform-modules v6 in the openshift4-terraform Commodore component.
> vshn-lbaas-exoscale: Manage Floaty IAMv3 role and credentials in Terraform

- modules/vshn-lbaas-cloudscale/README.md
- modules/vshn-lbaas-cloudscale/hiera.tf
- modules/vshn-lbaas-cloudscale/main.tf
- modules/vshn-lbaas-cloudscale/outputs.tf
- modules/vshn-lbaas-cloudscale/variables.tf
> Add optional support for using existing floating IPs

- modules/vshn-lbaas-cloudscale/hiera.tf
- modules/vshn-lbaas-cloudscale/main.tf
- modules/vshn-lbaas-cloudscale/variables.tf
- modules/vshn-lbaas-hieradata/templates/hieradata.yaml.tmpl
> vshn-lbaas-cloudscale: Add variables to control which cloudscale floating IPs to allocate

- modules/vshn-lbaas-exoscale/main.tf
- modules/vshn-lbaas-exoscale/variables.tf
We still default to 20GB disks to make the change non-breaking.
> vshn-lbaas-exoscale: Make LB disk size configurable

- modules/vshn-lbaas-cloudscale/README.md
- modules/vshn-lbaas-cloudscale/providers.tf
- modules/vshn-lbaas-exoscale/README.md
There's no breaking changes in the v5 provider which actually affect us.
> Bump minimum required cloudscale Terraform provider to 5.0
